### ISSUE TITLE
I don't see data source after restart

### ISSUE THREAD

**Issue by acappelletti** [VolkovLabs/volkovlabs-env-datasource#17]
Hi, 
I'm on last version of Grafana on my docker machine...(v9.2.6 (8ba6f0f1a8)) and I followed all the installation commands + restart.
grafana-cli --repo https://volkovlabs.io/plugins plugins install volkovlabs-env-datasource
but I didn't see any data source "env-datasource" I try also filtering simply "env".. but nothing appears to me.
Is it compatible with the last Grafana version?

ALEN

**Comment by mikhail-vl** [comment]
@acappelletti Environment Data Source is a Private plugins signed for `http://localhost:3000/`. It may not load if your Grafana configured for the specific domain.

  Because of the nature of the plugin it can not be included in the Grafana Catalog.
  We recommend to use NGINX in front of Grafana for security reasons and to keep the default domain as is, then you can use it.
  Other option is to compile and sign the plugin for your custom domain.

**Comment by mikhail-vl** [comment]
@acappelletti Another option is to make it unsigned and allow unsigned plugins: https://volkovlabs.io/plugins/grafana-allow-unsigned/

**Comment by acappelletti** [comment]
Hi Mikhail, 
I read carefully your post... I'm not an expert of NGINX... but I found some simple article to start with.
I build a stack using many app with portainer.io.

Do I necessarily have to use nGINX or Traefik.io, the latter could work also? 
They both look like proxy servers to me (I need to study syntax for each by the way.... to include in my docker compose file).

p.s.: Could you pass me a simple example of a docker compose with Grafana, NGINX and your plug if you have it?

ALEN

**Comment by mikhail-vl** [comment]
@acappelletti You can take a look at our repository. It has NGINX configuration for `docker-compose`: https://github.com/volkovlabs/volkovlabs-app
  
  Any proxy server will work. We use NGINX for all of our projects and clients in front of Grafana for an extra layer of protection.

  This should help you to get started:
```
version: '3.4'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    volumes:
      - ./volkovlabs-env-datasource:/var/lib/grafana/plugins/volkovlabs-env-datasource
      - ./provisioning:/etc/grafana/provisioning

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    environment:
      - GRAFANA_HOST=localhost
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana
```

  Check the repository for the NGINX configuration.
  Let me know if you have any questions.
