### ISSUE TITLE
Plugin `volkovlabs-env-datasource` not provisioning filter from datasource.yml on grafana 10.2.2

### ISSUE THREAD

**Issue by Nine-H** [VolkovLabs/volkovlabs-env-datasource#34]
No matter what I try I can't seem to get the filter to populate correctly, even with verbatim config from documentation.

**Comment by mikhail-vl** [comment]
@Nine-H Have you looked at the documentation and tried it: https://volkovlabs.io/plugins/volkovlabs-env-datasource/provisioning/ ?

```
datasources:
  - name: Environment
    type: volkovlabs-env-datasource
    access: proxy
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    jsonData:
      filter: GF_
```

**Comment by Nine-H** [comment]
yes. the data source that gets provisioned has an empty filter, I need to paste a filter in after the fact to use the filtering functionality.

**Comment by Nine-H** [comment]
Here's a minimal example to recreate:

`docker-compose.yml`
```
version: "3"
services:
  grafana-testenv:
    container_name: grafana-testenv
    environment:
      - GF_DEFAULT_INSTANCE_NAME=grafana-testenv
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password1
      - GF_INSTALL_PLUGINS=https://github.com/VolkovLabs/volkovlabs-env-datasource/releases/download/v3.1.0/volkovlabs-env-datasource-3.1.0.zip; volkovlabs-env-datasource
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/main.yaml
    image: grafana/grafana:10.2.2
    ports:
      - 3000:3000
 ```

`datasources.yml`
```
datasources:
  - name: Environment
    type: volkovlabs-env-datasource
    access: proxy
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    jsonData:
      filter: GF_
```

after I start the instance with `docker-compose up`...

empty filter:
![image](https://github.com/VolkovLabs/volkovlabs.io/assets/20123543/3467b295-1730-4c2d-b5ea-58f9c947ebf5)

environment variables not filtered:
![image](https://github.com/VolkovLabs/volkovlabs.io/assets/20123543/d5044021-3856-45a2-8cb9-31f5728fd540)

**Comment by mikhail-vl** [comment]
@Nine-H Thank you for providing details.

  I will check and get back to you.

**Comment by mikhail-vl** [comment]
@Nine-H I was able to reproduce the issue. I compared it to our provisioning configuration in the repository and found out that `apiVersion: 1` is required to set `jsonData`.

```
apiVersion: 1

datasources:
  - name: Environment
    type: volkovlabs-env-datasource
    access: proxy
    isDefault: true
    orgId: 1
    uid: P9E471951A1B4106E
    version: 1
    editable: true
    jsonData:
      filter: GF_
```

  I used the latest version v4 on Grafana 11.1.0: https://github.com/VolkovLabs/volkovlabs-env-datasource/releases/tag/v4.0.0
  Please update your provisioning configuration and let us know if there is anything else.
