### ISSUE TITLE
Automatic docker installation

### ISSUE THREAD

**Issue by ankhafizov** [VolkovLabs/volkovlabs-env-datasource#47]
```
grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana-oss:11.2.0-ubuntu
    depends_on:
      - influxdb
    environment:
      - TZ=Europe/Moscow 
      - GF_ALLOW_EMBEDDING=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - SERVER_IP=10.228.37.124
      - CAMERA_STREAM_PREFIX=go2rtc_
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_KEY=/etc/certs/grafana.key
      - GF_SERVER_CERT_FILE=/etc/certs/grafana.cert
    user: "472"
    ports:
      - "3111:3000"
    volumes:
      - ./services/grafana:/var/lib/grafana
      - ./ssl:/etc/certs/
    env_file:
      - secrets.txt
```

volkovlabs-env-datasource is not available when I start grafana, whereas dalvany-image-panel is available. Both of them are located in plugins folder. It is crutial, when I want to work with the plugin on private server without the Internet
